FROM node:20-alpine

RUN apk add --no-cache mysql-client

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY prisma ./prisma/

RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "-c", "npx prisma db push && node prisma/seed.js && npm run dev"]